version: "3"

services:
  node:
    container_name: node
    build: ./docker/node/
    image: node-scraper
    volumes:
      - ./:/app:cached
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    environment:
      PORT: ${PORT}
    command: [sh, -c, "npm install & pm2-runtime process.json"]
